version: "3.9"

services:
  proxy:
    hostname: proxy
    build: ./.devcontainer/proxy
    depends_on:
      - app
    ports:
      - "80:80"
    # volumes:
    #   - ./tmp/log/nginx:/var/log/nginx
  app:
    hostname: app
    build: ./.devcontainer/app
    tty: true
    volumes:
      - .:/go/src
